---
title: "HW04"
author: "Han Lee"
date: "3/5/2021"
output:
    html_document: default
    github_document: default
    theme: paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(here)
library(dplyr)
library(tidyr)
library(tibble)
library(ggplot2)
library(tidyverse)
library(gridExtra)
library(reshape2)
library(kableExtra)
library(ggdist)
```

```{r}

#Reading in data file and making sure all columns are correct and controlled for.
dat <- read_csv(here::here("raw_data","RepeatedExposureReverseRdata-3_13_2020.csv"),
                col_types = cols(
                  `F/L/Sex` = col_character(),
                  ID = col_double(),
                  TrialType = col_character(),
                  `Trial#` = col_double(),
                  `RunPosition#` = col_double(),
                  `Run#` = col_double(),
                  ConditionType = col_character(),
                  Condition = col_character(),
                  RT = col_double(),
                  Error = col_double(),
                  TotalError = col_double(),
                  Target = col_character(),
                  Globality = col_character(),
                  RunType = col_character(),
                  StimuliType = col_character()
                  ),
                  na=c("","NA")
                ) %>% 
    filter(TrialType == "Experiment", ConditionType == "Critical", Error == "0", (RT>=50 & RT<= 1999)) #Filtering out to relevant data (i.e., cleaning raw data)

#Creating clean csv file from filtering
write_csv(dat,
          here::here("Analyses", "HW04", "Data", "HW04_cleaned_data.csv")
          )

```

```{r}

#Histogram of RT distribution
graph = ggplot(dat) +
  aes(RT) +
  geom_histogram(binwidth = 50) #Bins are 50 msecs apart.


#Saving/outputing plots
ggsave(here::here("Analyses", "HW04", "Output", "Plots", "RTdististribution.pdf"), graph)

ggsave(here::here("Analyses", "HW04", "Output", "Plots","RTdististribution.svg"), graph)

ggsave(here::here("Analyses", "HW04", "Output", "Plots","RTdististribution.eps"), graph)
```

```{r}

#Creating summary table (mean and SD) by ID (within subject design), condition, and run position
summarytable = dat %>%
  group_by (ID, Condition, `RunPosition#`) %>% 
  summarize(across(c(RT),
                     list(Mu = ~ mean(.x,
                                      na.rm = TRUE
                                     ),
                         Sigma = ~ sd(.x,
                                      na.rm = TRUE
                                     ),
                         n = ~ n()
                         )
                  )
            )

#Saving/output summary table as a csv
write_csv(summarytable,
          here::here("Analyses", "HW04", "Output", "Summaries", "Mean_by_condition-id-conditiontype.csv")
          )

```
