---
title: "HW3"
author: "han"
date: "2/4/2021"
output:
    html_document: default
    github_document: default
    theme: paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gapminder)
library(tidyverse)
```

## R Markdown: HW3 Exercise 1 and 2

```{r cars}
#Exercise 1.1
#Use filter() to subset the gapminder data to three countries of your choice in the 1970’s.

Ex1.1=gapminder %>% 
  filter(country == "Mexico"& year %in% 1970:1980|country =="India"& year %in% 1970:1980|country =="China" & year %in% 1970:1980)

Ex1.1

#Exercise 1.2
#Use the pipe operator %>% to select “country” and “gdpPercap” from your filtered dataset in 1.1.

Ex1.1 %>% 
  select(country,gdpPercap)

#Exercise 1.3
#Make a new variable in gapminder for the change in life expectancy from the previous measurement. Filter this table to show all of the entries that have experienced a drop in life expectancy.
#Hint: you might find the lag() or diff() functions useful.

gapminder %>% #Adding new column
  group_by(country) %>% #Makes it so changes in life expectancy are only measured by country
  mutate(ChangeInLifeExp = lifeExp-lag(lifeExp)) %>%  #ChangeinLifeExp is the current row - previous row
  filter(ChangeInLifeExp<0) #Filters changes by negative values which represents decrease in life expectancy

#Exercise 1.4
#Filter gapminder so that it shows the max GDP per capita experienced by each country.
#Hint: you might find the max() function useful here.

gapminder %>% #Making table based on max GDP per capita by country
  group_by(country) %>% #Groups gapminder by country to isolate max gdpPer cap for each country
  filter(gdpPercap==max(gdpPercap)) #Filters only by max gdpPercap for each country

#Exercise 1.5
#Produce a scatterplot of Canada’s life expectancy vs. GDP per capita using ggplot2, without defining a new variable. That is, after filtering the gapminder data set, pipe it directly into the ggplot() function. In your plot, put GDP per capita on a log scale.

gapminder %>% #Making Scatterplot
  filter(country=="Canada") %>% 
  ggplot(aes(x=lifeExp, y=gdpPercap))+
  geom_point(size=2) + #Plots each point by life Exp and gdpPercap
  scale_y_continuous(trans='log10')+ #changes gdpPer cap scaling to log scale
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())


#Exercise 2: Explore two variables with dplyr and ggplot2 Use palmerpenguins::penguins or another dataset of your choice. (Check out a dataset from the datasets R package if you want!)

#Exercise 2.1
#Pick two quantitative variables to explore.
#Make a summary table of descriptive statistics for these variables using summarize().
#Include whatever staistics you feel appropriate (mean, median sd, range, etc.).
#Make a scatterplot of these variables using ggplot().

mtcars %>% #Making summary table
  summarize(mu_mpg = mean(mpg),#Mean mpg
          sigma_mpg=sd(mpg), #SD mpg
          mu_wt = mean(wt), #Mean wt
          sigma_wt=sd(wt)) #SD wt

mtcars %>% #Making scatterplot
  ggplot(aes(x=mpg, y=wt))+
  geom_point(size=2) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())


#Exercise 2.2
#Pick one categorical variable and one quantitative variable to explore.
#Make a summary table giving the sample size (hint: n()) and descriptive statistics for the quantitative variable by group.
#Make one or more useful plots to visualize these variables.

summary_mtcars=mtcars %>% #Making summary table
  mutate(cyl=as.factor(cyl)) %>% 
  group_by(cyl) %>% 
  summarize(mu_wt = mean(wt),
          sigma_wt=sd(wt),
          sample_size = n(),
          SE=sigma_wt/sqrt(sample_size))

summary_mtcars
            
mtcars %>% #Data visualization of car weights
  mutate(cyl=as.factor(cyl)) %>% 
  ggplot(aes(x=cyl,y=wt, fill=cyl))+
  geom_bar(stat="identity") +
  labs(title="Total weight of cars by Cyl", x ="Cyl", y = "Weight")+ #Relabeling
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())

  
```
