---
title: "HW1 - Cars dataset Finalized"
author: "Han"
date: "1/21/2021"
output:
    html_document: default
    github_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(rmarkdown)
library(ggpubr)
```

## HW1 Assignment

Dataset used: cars

<!-- Put blank lines between each paragraph, code chunk, etc. -->

Details regarding dataset cars

```{r Cars}
# Shows dataset
cars
# Summary data of cars dataset
summary(cars)
# Correlation of distance and speed
cor(cars$speed, cars$dist)
```

## Plots

<!-- In future assignements, please use ggplot() and build the plots up with individual geom_*() commands. It is worth the effort to learn to build ggplots manually rather than relying on pre-rolled functions. -->

```{r Plots, echo=FALSE}
# Scatter plot of the car dataset
sp <- ggscatter(cars, x = "speed", y = "dist",
   add = "reg.line",  # Add regressin line
   add.params = list(color = "blue", fill = "lightgray"), # Customize reg. line
   conf.int = TRUE, # Add confidence interval
   title = "Correlation between speed and distance" # Add title
   )
# Add correlation coefficient to plot
sp + stat_cor(method = "pearson", label.x = 3, label.y = 30)
#> `geom_smooth()` using formula 'y ~ x'# Plot means of car dataset # don't leave commented-out code in your final scripts.
```
