---
title: "HW1 - Cars dataset HL"
author: "Han"
date: "1/21/2021"
output: 
  html_document:
    keep_md: true
  theme: paper
  toc: true
  toc_float: true
  code_folding: "hide"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(rmarkdown)
library(ggpubr)
```

## HW1 Assignment

Dataset used: cars

Details regarding dataset cars
```{r Cars}
# Shows dataset
cars
# Summary data of cars dataset
summary(cars)
# Correlation of distance and speed
cor(cars$speed, cars$dist)
```

## Plots
```{r Plots, echo=FALSE}
# Scatter plot of the car dataset
sp <- ggscatter(cars, x = "speed", y = "dist",
   add = "reg.line",  # Add regressin line
   add.params = list(color = "blue", fill = "lightgray"), # Customize reg. line
   conf.int = TRUE, # Add confidence interval
   title = "Correlation between speed and distance" # Add title
   )
# Add correlation coefficient to plot
sp + stat_cor(method = "pearson", label.x = 3, label.y = 30)
#> `geom_smooth()` using formula 'y ~ x'# Plot means of car dataset
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
